### ISSUE TITLE
Adding a easy way to copy string and var name

### ISSUE THREAD

**Issue by Hamidrzash** [MohammadMD1383/Actionable#1]
Hi i have an idea for a useful tool that if you right  click in a var name or method name etc it will be copied automatically.. This is very useful when i have a long name for my variable and it will save a lot of my time😁

**Comment by MohammadMD1383** [comment]
Well. added `copy/cut word at caret` by the `v1.2.0`.
You can close this issue if the requested feature is implemented correctly

**Comment by MohammadMD1383** [comment]
you may wait until the plugin is distributed on the store. or download it now.
[Actionable-1.2.0.zip](https://github.com/MohammadMD1383/Actionable/files/7821354/Actionable-1.2.0.zip)

**Comment by Hamidrzash** [comment]
Wow well that was fast.. thank you so much
