### ISSUE TITLE
Add actions Delete/Сut/Copy/Select Params

### ISSUE THREAD

**Issue by vruzin** [MohammadMD1383/Actionable#13]
| - caret
For example Delete:
func DownloadFile(filepa|th string, url string) (err error) {
to
func DownloadFile(|, url string) (err error) {
----
x := a + b + ( c |+ (k+z+m) ) + v
to
x := a + b + ( | ) + v
----
a := "asdasd| asdasd asda asd 'asd'dasdad" 
to
a := "|" 
-----
k = zzz + as|sd(sd)[0].Param.fn('asd').Param["asd"+sds+'asd'] + kkk
to
k = zzz + | + kkk
==============
It will be very useful

**Comment by MohammadMD1383** [comment]
Hi,

Thanks for submitting the feature request.

I will try to implement a basic functionality of what you said and then moving forward by getting feedbacks.

**Comment by vruzin** [comment]
Thank you! To be honest, many of these features are sorely lacking. They seem to be very small and inconspicuous, but when they work on hot keys, the work is accelerated many times over.
Thanks for your help.

**Comment by vruzin** [comment]
It can be implemented in different ways. Ideally, if the system will understand the dialect. But you can also use regular expressions. For example, insert `№№№` in place of the cursor, and then apply the regular expression:

```(?<=[,{\[\(])[^,{\[\(]*?№№№[^,{\[\(]*?(?=[,\}\)\)])```

But in my example, there is no dependency on parentheses that may appear inside... for this you need to do with recursion in regular expressions.

By the way, it will be VERY cool if you can make it so that any user can independently create a regular expression and set it to a hotkey.

or make it so that when you press a hot key, a list of options is displayed. And each option can apply one or more regular expressions. And so that these regular expressions can be applied entirely to the line, for a block a few lines up and down, for a block from the cursor up a few lines, and from the cursor and down a few lines. So that the number of these lines can be set manually. It turns out that if you do this, you get super functional!

Of course, I have a lot of imagination :)

You can also do that when the cursor moves, automatically highlight the piece of code that is supposed to be Select / Cut / Copy / Delete ... Then it turns out it will be super visual ... But probably it will already slow down the system, so it's probably not worth it do

**Comment by MohammadMD1383** [comment]
Right,

I'm going to use psi elements to detect the parameters range in the text, that's going to be easy thanks to the power of the IDE.

**Comment by vruzin** [comment]
Cool! I think then such tasks should be much easier.

OK. Have a good day! Thanks for the answer.

**Comment by MohammadMD1383** [comment]
although the PR is closed, but this issue remains open to be implemented in future if possible

**Comment by MohammadMD1383** [comment]
You need these features for golang, right?

**Comment by MohammadMD1383** [comment]
up to now you can test the functionality for similar situations:

* _Remove a parameter_
  ```go
  func test(param1 string, param2 int) { }
  ```

* _Remove an element under caret_
  ```go
  str := "Hello World"
  ```

get the latest nightly build from [releases page](https://github.com/MohammadMD1383/Actionable/releases/)

**Comment by MohammadMD1383** [comment]
from now you can also delete operands in binary expressions like below:

```go
bin_expr := 123 + 788 - 1111
bin_expr2 := "hello" + "wordl" + 545454
```

**Comment by MohammadMD1383** [comment]
@JasonGmitter these actions are available for the following languages:
* java
* kotlin
* javascript/typescript
* golang

**Comment by MohammadMD1383** [comment]
now copy/cut is also supported

done!
