### ISSUE TITLE
Feature Request: Delete to BOL but not include indents

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#18]
**Current behavior:**

Before:
`<tab><tab>Hi!|`
After:
`|`

**New action:**

Before:
`<tab><tab>Hi!|`
After:
`<tab><tab>|`

https://github.com/vsch/MissingInActions/blob/4f2f9c1264144ed9e2db082614c57cb48eb8328b/src/com/vladsch/MissingInActions/actions/line/DeleteToLineStartIndentAction.java DeleteToLineStartIndentAction

**Comment by MohammadMD1383** [comment]
So, what will happen in the below situation?

```
              Hello | World

1:
              | World
2:
              |
```

**Comment by MohammadMD1383** [comment]
> So, what will happen in the below situation?
> 
> ```
>               Hello | World
> 
> 1:
>               | World
> 2:
>               |
> ```

well, both cases has been implemented:
1. Delete to Indented Line Start
2. Empty Line Preserving the Indent

**Comment by j-a-s-o-n-g** [comment]
Ah yes, when you press the action and the line only contains indent, it will delete to line start completely.

**Comment by MohammadMD1383** [comment]
> Ah yes, when you press the action and the line (to the left) only contains indent, it will delete to line start completely.

well, so I have to edit it ...

**Comment by j-a-s-o-n-g** [comment]
Oh no that’s what the original addon did.On Jan 17, 2023, at 9:11 AM, Mohammad Mostafa Dastjerdi ***@***.***> wrote:﻿
Reopened #18.

**Comment by MohammadMD1383** [comment]
done!

**Comment by j-a-s-o-n-g** [comment]
I noticed something odd that may or may not be a desired effect. If you have any text to the right of the caret, it will not clear the indent to the left when there is no non space character to first erase.

Current:
`
····var omg| = "hi";
`
Run command.
`
····| = "hi";
`
Run command.
`
····| = "hi";
`


Expected:
`
····var omg| = "hi";
`
Run command.
`
····| = "hi";
`
Run command.
`
| = "hi";
`

**Comment by MohammadMD1383** [comment]
https://github.com/MohammadMD1383/Actionable/blob/69135c332ab38dafec7cb7335600178befb79293/src/main/java/ir/mmd/intellijDev/Actionable/editing/DeleteToIndentedLineStartAction.kt#L22-L26

well, this is as designed ... but I can change it

for now you may use the IDE action to do this

**Comment by j-a-s-o-n-g** [comment]
I couldn't remember if it was as designed or not. But after playing with it the last day it feels like an enhancement, or "nice to have". No rush on it!

**Comment by MohammadMD1383** [comment]
sounds good!

so should this be closed?

**Comment by j-a-s-o-n-g** [comment]
You can close this if you don't want to implement the extra behavior. I think it would be a good addition.

**Comment by MohammadMD1383** [comment]
I'm really busy now but I will implement it
