### ISSUE TITLE
Feature Request: Tweak Select literal element.

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#20]
Select literal element under cursor selects quote characters on first keypress, then on second press selects contents within the quotes.

It would be nice to first select the content between the quotes on first keypress, then include quotes on second keypress. 

Thanks!

**Comment by j-a-s-o-n-g** [comment]
Can I get a **new** action that selects between quotes instead of always running the keybind twice?

**Comment by MohammadMD1383** [comment]
ok, please create a new issue for that, I will work on that if possible. Thanks.

**Comment by MohammadMD1383** [comment]
something inspired to my mind, I don't know if it works, but it worth it a try:

You may be able to record a macro of executing the action twice and then assign a shortcut to that macro!

**Comment by j-a-s-o-n-g** [comment]
Or we could just have an AWESOME universal "Select between quotes" command that works in all languages **_and_** plain text. 🎉 👍
