### ISSUE TITLE
Feature Request: Dock tabs to left/top/right/bottom command and keybind

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#27]
In the Settings, you're able to dock the tabs in the viewport, but there is no keyboard shortcut or command for it. Can you look into this to see if it's possible?

![image](https://user-images.githubusercontent.com/42372270/213229061-e5115261-f7f7-4d3d-81ea-92a4a1b42e9f.png)

**Comment by MohammadMD1383** [comment]
Hmm... I can't figure out what exactly you mean.

Could you please describe more? Or even upload a gif to show what you mean?

**Comment by j-a-s-o-n-g** [comment]
1.) Go to Settings > Editor > General > Editor tabs.
2.) Change tab placement to left. 
3.) Apply
4.) Open several files in an editor, you'll see the tabs stack on the left.

Repeat 1-4 but instead of left, choose top.

Request: A "search everything" command as well as a keybind for each of the tab placements to swap them without having to go into settings.

**Comment by MohammadMD1383** [comment]
![image](https://user-images.githubusercontent.com/69088224/213359131-6aa0b171-b2b3-4945-82ba-92b6d33f3f9c.png)

well as you see in the picture this is already possible, I don't know if it works on older IDE versions, but it does work on `2022.3.2 RC`

**Comment by j-a-s-o-n-g** [comment]
Can we still add key binds?

**Comment by MohammadMD1383** [comment]
This should be possible but I can't assign any shortcut to any action from the **_Actions Search_** tab (using `ctrl+.`). this may be a bug of the IDE ?!

**Comment by j-a-s-o-n-g** [comment]
If it is a bug, it's been like that for a while. That's why I was hoping you could wire together a way to with new commands/keybinds.

**Comment by j-a-s-o-n-g** [comment]
Hey,

After playing with your addon more I came across the macro section of the settings and I can’t seem to figure out how to make any macros with it. Is it just an unfinished panel or am I missing something. I also looked at your documentation section of your github and it wasn’t documented. 

Also I was wondering how the predict functionality works too. 

Soon I am planning on writing documentation for your GitHub page to help out. On the stuff I know how to do of course. 😅

Jason

**Comment by MohammadMD1383** [comment]
to add a macro you need to first select a text and then invoke `add selection to macros` action.

after that you can assign a shortcut to that macro and use it everywhere in an editor.


predict words is not really good at doing what it is intended to, but it can be useful sometimes. for instance you can write `helloworldclass` and then invoke predict pascal case words action and hope it will change it to `HelloWorldClass`.

this actually works by the help of grazie plugin (which detects grammar issues and typos), it tries to find largest words that doesn't have a typo, and then transform them to the desired form.


and for the documentation, I will appreciate your help. actually I was looking for someone to help me do that. Thanks in advance.

**Comment by MohammadMD1383** [comment]
https://github.com/MohammadMD1383/Actionable/blob/fb0e5d044aa8ec3c468bfcd9a23790eb0702643c/src/main/java/ir/mmd/intellijDev/Actionable/caret/justification/Actions.kt#L7-L28

to provide documentation you should use the `@Document` annotation and use it exactly like you see in the above example because I use regex to extract it.


then by executing docgen.py the new documentation should be added to the `docs/` directory, and I'm ready to accept your PR.
