### ISSUE TITLE
Feature request: Select line content excluding whitespace

### ISSUE THREAD

**Issue by KnifeFed** [MohammadMD1383/Actionable#28]
I would love an action that selects the content of the line, without the whitespace.
Basically what the [Perfect Line](https://marketplace.visualstudio.com/items?itemName=erhise.perfect-line-selection) VSCode extension does. A bonus would be a separate action that works the same but copies the content instead of selecting it.

**Comment by MohammadMD1383** [comment]
Thanks for the feature request!

These three new actions were implemented:
* copy line content without extra white-space (both start/end)
* cut line content without extra white-space (both start/end)
* select line content without extra white-space (both start/end)

**Comment by MohammadMD1383** [comment]
wait for the `v3.14.0`

**Comment by KnifeFed** [comment]
Awesome, thank you!
