### ISSUE TITLE
Feature Request: Keybind to get to keybinds..

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#33]
As of the latest version, IntelliJ has stealth removed the ability to bind to the keymap configuration screen. You can keybind to the keybind selector context menu, but not to the settings page. It would be nice to restore this functionality.

Here's a link to the settings window: jetbrains://idea/settings?name=Keymap

**Comment by MohammadMD1383** [comment]
fcd0505a8307c844049d36e8d059bff038a09f47

**Comment by j-a-s-o-n-g** [comment]
Thanks! Works perfectly!
