### ISSUE TITLE
Feature Request - Replace carets (refactor dialog box) and convert to case

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#38]
Similar to #37, this is something I do all the time, but never think twice that there should be a better way of doing it. Basically it sums down to this-- As developers, sometimes the fastest way to add new functionality is to paste or duplicate other code and tweak variable names. So you might have this piece of code:

```var decrement = this.props.shouldDecrementValue();```

And say you now want to add a new method called `shouldIncrementValue`. Naturally you will duplicate that line above and replace "de" with "in" like so:

```
var decrement = this.props.shouldDecrementValue();
var increment = this.props.shouldIncrementValue();
```

But as you'll notice that the first change was all lowercase "in" and in the method, it's camelcased "In". This is a simple problem with 2 locations where you will want to change casing, but if you're refactoring a complex method and changing a variable name in dozens of locations, this will take a lot more work.

**Solution: it would be faster to update all carets by only typing your changes once instead of for x times you need replaced.**

```
var decrement = this.props.shouldDecrementValue();
var decrementVariationA = "variation a";
var decrementVariationB = "variation b";
var decrementVariationC = "variation c";
var decrementVariationD = "variation d";

function shouldDecrementValue(etc) {
  var thisDecrement = "";
  var thisDecrementArray = [];
}
```

1.) Before: Key: [] = selection range, | is cursor

```
var [decrement]| = this.props.should[Decrement]|Value();
var [decrement]|VariationA = "variation a";
var [decrement]|VariationB = "variation b";
var [decrement]|VariationC = "variation c";
var [decrement]|VariationD = "variation d";

function should[Decrement]|Value(etc) {
  var this[Decrement]| = "";
  var this[Decrement]|Array = [];
}
```

2.) Execute action, a **single line input dialog box** comes up, you enter in your new word in all lowercase: "increment"

3.) After action: Key: [] = selection range, | is cursor

```
var increment| = this.props.shouldIncrement|Value();
var increment|VariationA = "variation a";
var increment|VariationB = "variation b";
var increment|VariationC = "variation c";
var increment|VariationD = "variation d";

function shouldIncrement|Value(etc) {
  var thisIncrement| = "";
  var thisIncrement|Array = [];
}
```

_Note: The result caret placement isn't even important if it makes it easier._

It will predict which casing you are replacing and fill it in accordingly. Again, this is essentially #37 but instead of using the clipboard, you are typing your replacement into a dialog box.

**Comment by MohammadMD1383** [comment]
nice!
