### ISSUE TITLE
Feature Request: Duplicate Line or Selection for Carets (with Dialog input instead of clipboard)

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#39]
Relates to #37 and #19.

Potentially helpful links:
- https://www.codepedia.org/ama/how-to-use-input-dialog-in-intellij-plugin
- https://jetbrains.design/intellij/controls/text_area/
- https://plugins.jetbrains.com/docs/intellij/dialog-wrapper.html#usage

Instead of using Clipboard on action, open up a multi line text box for direct input and using the content of the popup box as the reference.

It's convenient to pop up an input box popup because of how people's minds work. They usually want to execute the action before typing and copying their content into the clipboard first.

Say you have this:

``` JSX
<Route path='/products' component={Products} />
```

Key: [] selection bounds | caret.

``` JSX
<Route path='/[products]|' component={[Products]|} />
```

Execute action, multiline input box comes up with OK and Cancel button.

Type in:
``` Text
home
products
about
careers
```

Press OK

Results: Key:  | caret.
``` JSX
<Route path='/home|' component={Home|} />
<Route path='/products|' component={Products|} />
<Route path='/about|' component={About|} />
<Route path='/careers|' component={Careers|} />
```

Note: #37 implements a settings toggle (that can be bound to keybind and toolbar) that will decide if this will paste normally or preserve case for all Actionable commands. Preserving case won't be enabled by default.

**Without** preserving case toggled **ON,** the result would be:

``` Text
home
PRODUCTS
about
Careers
```

``` JSX
<Route path='/home|' component={home|} />
<Route path='/PRODUCTS|' component={PRODUCTS|} />
<Route path='/about|' component={about|} />
<Route path='/Careers|' component={Careers|} />
```

**Comment by MohammadMD1383** [comment]
working on it ...

**Comment by MohammadMD1383** [comment]
from now `preserve-case` works
