### ISSUE TITLE
Feature Request - Move Cursor to next Matching PSI Element (+ with selection)

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#40]
Say I have this: Key | is caret

``` javascript
const obj = {
  '|': '',
  '': '',
  '': '',
  '': '',
  '': '',
}
```

And I want to quickly fill out each string between ''. Currently there is no efficient way to move the cursor onto the next string element.

``` javascript
const obj = {
  '': '|',
  '': '',
  '': '',
  '': '',
  '': '',
}
```

``` javascript
const obj = {
  '': '',
  '|': '',
  '': '',
  '': '',
  '': '',
}
```

``` javascript
const obj = {
  '': '',
  '': '|',
  '': '',
  '': '',
  '': '',
}
```

(and so forth)

![image](https://user-images.githubusercontent.com/42372270/221049930-a8f32d21-4dc0-4719-9036-406810010f9a.png)

So if your cursor is on PsiElement(JS:STRING_LITERAL) and you execute the command, your cursor will jump to the next  PsiElement(JS:STRING_LITERAL).

In theory, this will jump the cursor between each empty ''. Right?

In addition, it would be cool to select next matching psi element as well. 

``` javascript
const obj = {
  '|text': 'more',
  'text': 'more'
```

Execute Move Cursor to Next Matching PSI Element With Selection:

``` javascript
const obj = {
  '[text]|': 'more',
  'text': 'more'
```

Execute Move Cursor to Next Matching PSI Element With Selection:

``` javascript
const obj = {
  '[text]': '[more]|',
  'text': 'more'
```

Execute Move Cursor to Next Matching PSI Element With Selection:

``` javascript
const obj = {
  '[text]': '[more]',
  '[text]|': 'more'
```

_Note: I notice that your cursor's PSI element is set to the new element when the cursor has changed position, so it would have to remember what was previously selected or else it will keep re-sampling new PSI elements each time it's selected something. You might need to have one command that "sets" the PSI element, then the Action would move/select based on what was "set"._

If this is too complex, you could always just implement a "Move to next _empty_ edit location" function.

**Comment by MohammadMD1383** [comment]
working on this ...

**Comment by MohammadMD1383** [comment]
from now `preserve-case` works.

**Comment by j-a-s-o-n-g** [comment]
Works great! One small issue is that if the next or previous occurrence is off screen, it doesn't scroll/adjust the view to show it.
