### ISSUE TITLE
Newer nightly build versions are coming up as older than official releases.

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#75]
![image](https://user-images.githubusercontent.com/42372270/231902701-1bcc5a84-6bab-4a7c-beb2-10c5b67de1cc.png)

I suspect due to the manifest generating:
`Version: nightly-4.2.0+e9918af`

**Comment by MohammadMD1383** [comment]
This should be solved in the latest nightly release.
